ort:
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  # Force overwriting of any existing output files.
  forceOverwrite: true

  # Package configurations have to be unique by ID and provenance. Ensure that different providers do not provide
  # configurations for the same package, see https://github.com/oss-review-toolkit/ort/issues/6972 for details.
  packageConfigurationProviders:
  - type: DefaultDir
  - type: OrtConfig

  # Package curation providers are listed from highest to lowest priority. Technically, they are applied in reverse
  # order: The provider with the highest priority is applied last, so it can overwrite any previously applied curations.
  packageCurationProviders:
  - type: DefaultFile
  - type: DefaultDir
  - type: OrtConfig
    enabled: '${USE_ORT_CONFIG_CURATIONS:-true}'

  severeIssueThreshold: ERROR
  severeRuleViolationThreshold: ERROR

  analyzer:
    allowDynamicVersions: true

    # A list of enabled package managers.
    enabledPackageManagers: [Maven, Npm]

    # A list of disabled package managers. Disabling a package manager here overrides enabling it in
    # `enabledPackageManagers`.
    disabledPackageManagers: [Gradle]

    # A flag to control whether excluded scopes and paths should be skipped during the analysis.
    skipExcluded: true

    packageManagers:
      Npm:
        options:
          # Option to only analyze direct dependencies
          ignore_transitive_dependencies: true
          # Ignore devDependencies
          ignore_dev_dependencies: true
        
      Yarn2:
        options:
          # If set to true, disable verification of HTTPS certificate of remote registries. Useful when using a proxy to
          # intercept requests to the registry.
          disableRegistryCertificateVerification: false

      Conan:
        # Holds a name of the lockfile. Required if allowDynamicVersions = false.
        # The lockfile should be located in the same directory as the conanfile.py or conanfile.txt.
        options:
          lockfileName: "lockfile.lock"

  downloader:
    allowMovingRevisions: true

    # A flag to control whether excluded scopes and paths should be skipped during the download.
    skipExcluded: true

    sourceCodeOrigins: [VCS, ARTIFACT]

