<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>io.mend.lens</groupId>
	<artifactId>lens-maven</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>lens-{{package}}</name>
	<description>Lens DeepScan template project for Maven</description>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>{{groupId}}</groupId>
			<artifactId>{{artifactId}}</artifactId>
			<version>{{version}}</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>central</id>
			<name>Maven Central</name>
			<url>https://repo1.maven.org/maven2</url>
		</repository>
		<repository>
			<id>google</id>
			<name>Google Android</name>
			<url>https://maven.google.com</url>
		</repository>
		<repository>
			<id>jboss</id>
			<name>JBoss</name>
			<url>https://repository.jboss.org/nexus/content/repositories/releases/</url>
		</repository>
		<repository>
			<id>atlassian</id>
			<name>Atlassian</name>
			<url>https://packages.atlassian.com/maven-public/</url>
		</repository>
		<repository>
			<id>confluent</id>
			<name>Confluent - Kafka</name>
			<url>https://packages.confluent.io/maven/</url>
		</repository>
		<repository>
			<id>imagej</id>
			<name>ImageJ Public</name>
			<url>https://maven.imagej.net/content/repositories/public/</url>
		</repository>
		<!-- requires authentication 
		<repository>
			<id>icm</id>
			<name>ICM Repository</name>
			<url>https://maven.icm.edu.pl/artifactory/repo/</url>
		</repository>
		-->
	</repositories>
</project>
